control_frequency: 15.0
gripper_mode: "absolute_continuous"
max_episode_steps: 1500

observations_to_include_to_state:
  - observation.state.cartesian
  - observation.state.gripper
  - observation.state.joints
  - observation.state.target

cartesian_control_param_config: null
joint_control_param_config: null

robot_config:
  robot_type: "franka"
  current_pose_topic: "current_pose"
  target_pose_topic: "target_pose"
  target_joint_topic: "target_joint"
  current_joint_topic: "joint_states"
  current_twist_topic: "current_twist"
  publish_frequency: 50.0

gripper_config:
  min_value: 0.0
  max_value: 1.0
  command_topic: "/right/gripper/gripper_position_controller/commands"
  joint_state_topic: "/right/gripper/joint_states"
  index: 0
  publish_frequency: 30.0
  max_delta: 1.0

camera_configs:
  - camera_name: "robot0_eye_in_hand"
    camera_frame: "robot0_eye_in_hand_color_optical_frame"
    resolution: [256, 256]
    camera_color_image_topic: "/robot0_eye_in_hand/color/image_raw"
    camera_color_info_topic: "/robot0_eye_in_hand/color/camera_info"
  - camera_name: "robot0_agentview_left"
    camera_frame: "robot0_agentview_left_color_optical_frame"
    resolution: [256, 256]
    camera_color_image_topic: "/robot0_agentview_left/color/image_raw"
    camera_color_info_topic: "/robot0_agentview_left/color/camera_info"
  - camera_name: "robot0_agentview_right"
    camera_frame: "robot0_agentview_right_color_optical_frame"
    resolution: [256, 256]
    camera_color_image_topic: "/robot0_agentview_right/color/image_raw"
    camera_color_info_topic: "/robot0_agentview_right/color/camera_info"

sensor_configs: []
