control_frequency: 30.0
gripper_mode: "absolute_continuous"
max_episode_steps: null

observations_to_include_to_state:
  - observation.state.cartesian
  - observation.state.gripper
  - observation.state.joints
  - observation.state.target

cartesian_control_param_config: null
joint_control_param_config: null

robot_config:
  from_yaml: robots/fr3_root_home_lab.yaml

gripper_config:
  from_yaml: grippers/fr3_root_normalized_direct.yaml

camera_configs: []
sensor_configs: []
