control_frequency: 15.0
gripper_mode: "absolute_continuous"
max_episode_steps: 1500

observations_to_include_to_state:
  - observation.state.cartesian
  - observation.state.gripper
  - observation.state.joints
  - observation.state.target

cartesian_control_param_config: null
joint_control_param_config: null

robot_config:
  from_yaml: robots/fr3_root_home_neutral.yaml

gripper_config:
  from_yaml: grippers/fr3_right_normalized_direct.yaml

camera_configs:
  - from_yaml: cameras/robot0_eye_in_hand_256.yaml
  - from_yaml: cameras/robot0_agentview_left_256.yaml
  - from_yaml: cameras/robot0_agentview_right_256.yaml

sensor_configs: []
