leader:
  robot_type: "franka"
  publish_frequency: 50.0

leader_gripper:
  min_value: 0.0
  max_value: 1.0
  joint_state_topic: /right/gripper/joint_states
  command_topic: /right/gripper/gripper_position_controller/commands

gravity_compensation_controller: control/gravity_compensation.yaml

leader_namespace: right
leader_gripper_namespace: right/gripper

use_gripper: true
disable_gripper_torque: false
