robot_type: "franka"
home_config:
  - -1.73960110e-02
  - 9.55319758e-02
  - 8.09703053e-04
  - -1.94272034
  - -4.01435784e-03
  - 2.06584183
  - 7.97426445e-01
current_pose_topic: "current_pose"
target_pose_topic: "target_pose"
target_joint_topic: "target_joint"
current_joint_topic: "joint_states"
current_twist_topic: "current_twist"
publish_frequency: 50.0
