camera_name: "robot0_eye_in_hand"
camera_frame: "robot0_eye_in_hand_color_optical_frame"
resolution: [256, 256]
camera_color_image_topic: "/robot0_eye_in_hand/color/image_raw"
camera_color_info_topic: "/robot0_eye_in_hand/color/camera_info"
